project:
  type: website

website:
  title: "my_blog"
  navbar:
    right:
      - index.qmd
      - olympicsWeather.html
      - icon: github
        href: https://github.com/mjamin7
format:
  html:
    theme: morph
    css: styles.css

editor:
  name: rstudio
  path: C:/Users/mathi/OneDrive/Bureau

