project:
  type: website

website:
  title: "my_blog"
  navbar:
    right:
      - about.md
      - olympicsWeather.qmd
      - icon: github
        href: https://github.com/mjamin7
format:
  html:
    theme: quartz
    css: custom.css

editor: rstudio