project:
  type: website

website:
  title: "my_blog"
  navbar:
    right:
      - about.md
      - icon: github
        href: https://github.com/votre_nom
      - icon: linkedin
        href: https://www.linkedin.com/in/votre_profil
format:
  html:
    theme: flatly
    css: custom.css

editor: vscode
